version: '3.4'
services:

  mysql:
    container_name: 'mysql'
    image: mysql:8.0.32
    restart: always
    network_mode: host
    environment:
      MYSQL_DATABASE: ledger
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "YES"

  ledger:
    container_name: 'ledger'
    build:
      context: ./
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ledger?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysql

