FROM ubuntu:16.04
WORKDIR /

COPY ./futuopend/FutuOpenD_7.1.3308_NN_Ubuntu16.04.tar.gz /
RUN \
    tar xvf /FutuOpenD_7.1.3308_NN_Ubuntu16.04.tar.gz && \
    mv FutuOpenD_7.1.3308_NN_Ubuntu16.04/FutuOpenD_7.1.3308_NN_Ubuntu16.04 /futuopend && \
    rm -rf /FutuOpenD_7.1.3308_NN_Ubuntu16.04.tar.gz /FutuOpenD_7.1.3308_NN_Ubuntu16.04 \
VOLUME /config
EXPOSE 11111
EXPOSE 22222
EXPOSE 33333
ENTRYPOINT ["/futuopend/FutuOpenD", "-cfg_file=/config/FutuOpenD.xml"]