version: '3.4'
services:
  ledger:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: 'host'


  mysql:
    container_name: 'mysql'
    image: mysql:8.0.32
    network_mode: 'host'
    restart: always
