@startuml
'https://plantuml.com/object-diagrm

object Account {
    autoId: Number 自动ID primary key

    accountId: String 账户ID UNIQUE
    rootAccountId: String 根账户ID
    parentAccountId: String 父账户ID

    depth: Number 深度
    name: String 帐号名称
    createTime: Timestamp 记录创建时间
    updateTime: Timestamp 记录更新时间
}

object Transaction {
    autoId: Number 自动ID primary key

    transactionId: String 交易ID
    sourceAccountId: Number 出资方帐号ID
    destinationAccountId: Number 目的出资方帐号ID
    amount: Number 资金额度
}

'object AccountCashFlow {
'    accountCashFlowId: Number 记录ID primary key
'    dstAccountId: Number 资金目的地账户ID
'    srcAccountId: Number 资金源账户ID
'    amount: Number 资金总额度
'    bookBalance: 当前账面余额
'    date: Date 资金发生日期
'    dateOrder: Number 资金发生日排序
'    subAccountCashFlow: Array<SubAccountCashFlow> 分单
'}


'object Fund {
'    code: String 基金代码 primary key
'    name: String 基金名称
'    netWorth: Number 基金净值
'    netWorthDate: Date 基金净值最后更新日期
'    createTime: Timestamp 记录创建时间
'    updateTime: Timestamp 记录更新时间
'}

'object Stock {
'    code: String 股票代码 primary key
'    name: String 股票名词
'    price: String 股票价格
'    createTime: Timestamp 记录创建时间
'    updateTime: Timestamp 记录更新时间
'}

'object FundFlow {
'    fundFlowId: Number 记录ID primary key
'    code: string 基金代码 foreign key
'    dividend: String
'    netWorth: Number
'    dayGrowth: Number
'}


'FundFlow::code --o Fund : 聚合

@enduml
